name: Scrape interest rate data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '7 7,19 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest interest rate
      run: |-
        NOW=$(date +'%Y-%m-%d')
        declare -A ir
        # Korea
        ir[INTDSRKRM193N]="1964-01-01"
        # USA
        ir[INTDSRUSM193N]="1950-01-01"
        # Japan
        ir[INTDSRJPM193N]="1953-01-01"
        for i in "${!ir[@]}"
        do
          curl -s "https://fred.stlouisfed.org/graph/fredgraph.csv?mode=fred&ts=12&tts=12&id=INTDSRKRM193N&cosd=${ir[$i]}&fq=Monthly&vintage_date=${NOW}&revision_date=${NOW}&nd=${ir[$i]}" > "interest-rate/${ir[$i]}.csv"
        done
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
