name: Scrape interest rate data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '7 0 4,14,24 * *'

jobs:
  scrape-ir:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest interest rate
      run: |-
        NOW=$(date +'%Y-%m-%d')
        FROM="1950-01-01"
        declare -A ir
        # Korea
        ir[INTDSRKRM193N]="intdsr_korea"
        # USA
        ir[INTDSRUSM193N]="intdsr_usa"
        # Japan
        ir[INTDSRJPM193N]="intdsr_japan"
        for i in "${!ir[@]}"
        do
          curl -s "https://fred.stlouisfed.org/graph/fredgraph.csv?mode=fred&ts=12&tts=12&id=${i}&cosd=${FROM}&fq=Monthly&vintage_date=${NOW}&revision_date=${NOW}&nd=${FROM}" > "interest-rate/${ir[$i]}.csv"
        done
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
