name: Scrape interest rate data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '7 7,19 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest interest rate
      run: |-
        NOW=$(date +'%Y-%m-%d')
        curl -s https://fred.stlouisfed.org/graph/fredgraph.csv?mode=fred&ts=12&tts=12&id=INTDSRKRM193N&cosd=1964-01-01&coed=2020-06-01&fq=Monthly&vintage_date=${NOW}&revision_date=${NOW}&nd=1964-01-01 > "interest-rate/korea.csv"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
