name: Scrape latest naver finance data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '15 7 * * 1-5'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      R_LIBS: ~/.local/share/rlibs

    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
  
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.3' # The R version to download (if necessary) and use.
    - run: Rscript -e 'print("hello")'

    # https://github.com/actions/cache/blob/main/examples.md#r---renv
    - uses: actions/cache@v2
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Install system packages
      run: sudo apt install libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Restore packages
      shell: Rscript {0}
      run: |
        dir.create("${{ env.RENV_PATHS_ROOT }}", recursive = TRUE)
        .libPaths("${{ env.RENV_PATHS_ROOT }}")
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()

    - name: prepare Arrow
      run: Rscript -e 'library(arrow);arrow::install_arrow()'
  
    - name: run hello
      run: Rscript hello.R
    
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
